[[constraint]]
  name = "github.com/deislabs/porter"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
